# Generated by Django 5.1.2 on 2025-01-06 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auction_list_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solder', to=settings.AUTH_USER_MODEL),
        ),
    ]
