# Generated by Django 5.1.2 on 2025-01-16 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_create_time_comment_create_time_remove_bid_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='watcher',
            field=models.ManyToManyField(blank=True, related_name='watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
