# Generated by Django 5.1.2 on 2025-01-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_list_watcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_list',
            name='watcher',
        ),
        migrations.AddField(
            model_name='user',
            name='watchitem',
            field=models.ManyToManyField(blank=True, related_name='watch_list', to='auctions.auction_list'),
        ),
    ]
