# Generated by Django 5.1.2 on 2025-01-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_auction_list_watcher_user_watchitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_list',
            old_name='bidprice',
            new_name='startbidprice',
        ),
    ]
