# Generated by Django 5.1.2 on 2025-01-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_bidprice_auction_list_startbidprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='buyer',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auction_list',
            name='highestbid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
