# Generated by Django 5.1.2 on 2025-01-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auction_list_buyer_auction_list_highestbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_list',
            old_name='buyer',
            new_name='bider',
        ),
    ]
