# Generated by Django 5.1.2 on 2025-01-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_buyer_auction_list_bider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_list',
            old_name='bider',
            new_name='highestbider',
        ),
    ]
