# Generated by Django 5.1.2 on 2025-01-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_rename_bider_auction_list_highestbider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='highestbider',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
