# Generated by Django 5.1.2 on 2025-01-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_auction_list_highestbider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='url',
            field=models.URLField(max_length=600),
        ),
    ]
