# Generated by Django 5.1.2 on 2025-03-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_category_alter_auction_list_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='category',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
